theme = "ayu_mirage"

[editor.soft-wrap]
enable = true

[editor]
true-color = true

[keys.normal]
"A-g" = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]

[keys.insert]
"C-c" = "normal_mode"

[keys.select]
"C-c" = ["collapse_selection", "normal_mode"]

[editor.inline-diagnostics]
# Minimum severity to show a diagnostic on the primary cursor's line.
# Note that `cursor-line` diagnostics are hidden in insert mode.
cursor-line = "hint"
# Minimum severity to show a diagnostic on other lines:
other-lines = "error"
